from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import time
from contextlib import asynccontextmanager

from app.config import settings
from app.database.postgres_db import postgres_db
from app.utils.logger import setup_logger, get_logger
from app.api.routes import books, search, embeddings, stats, websocket
from app.services.book_service import book_service

# Setup logger
setup_logger()
logger = get_logger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Lifespan context manager for startup and shutdown events."""
    # Startup
    logger.info("Starting Calibre OpenClaw Server...")
    postgres_db.initialize_pool()
    logger.info("PostgreSQL connection pool initialized")
    
    # Background sync task
    async def background_sync():
        """Run book sync in background thread with periodic checks."""
        from pathlib import Path
        import asyncio
        from app.services.embedding_service import embedding_service
        try:
            # Reconcile embedding version before anything else so a model change
            # invalidates stale embeddings (regenerated by the worker afterwards).
            try:
                result = await asyncio.to_thread(
                    embedding_service.reconcile_embedding_version
                )
                logger.info(f"Embedding version reconciliation: {result}")
            except Exception as e:
                logger.error(f"Embedding version reconciliation failed: {e}")

            calibre_db_path = Path(settings.CALIBRE_DB_PATH)
            
            # Initial sync
            if calibre_db_path.exists():
                current_mtime = calibre_db_path.stat().st_mtime
                stored_mtime = postgres_db.get_calibre_db_mtime()
                
                if stored_mtime is None:
                    logger.info("First run - syncing all books from Calibre in background")
                    synced_count = await asyncio.to_thread(book_service.sync_books_from_calibre)
                    postgres_db.set_calibre_db_mtime(current_mtime)
                    logger.info(f"Initial sync completed: {synced_count} books")
                elif current_mtime > stored_mtime:
                    logger.info(f"Calibre DB updated (old: {stored_mtime}, new: {current_mtime}) - syncing in background")
                    synced_count = await asyncio.to_thread(book_service.sync_books_from_calibre)
                    postgres_db.set_calibre_db_mtime(current_mtime)
                    logger.info(f"Sync completed: {synced_count} books")
                else:
                    logger.info("Calibre DB is up to date - no sync needed")
            else:
                logger.warning(f"Calibre DB not found at {settings.CALIBRE_DB_PATH}")
            
            # Periodic sync check every 60 seconds
            while True:
                await asyncio.sleep(60)
                
                if calibre_db_path.exists():
                    current_mtime = calibre_db_path.stat().st_mtime
                    stored_mtime = postgres_db.get_calibre_db_mtime()
                    
                    if current_mtime > stored_mtime:
                        logger.info(f"Calibre DB updated detected (old: {stored_mtime}, new: {current_mtime}) - syncing")
                        synced_count = await asyncio.to_thread(book_service.sync_books_from_calibre)
                        postgres_db.set_calibre_db_mtime(current_mtime)
                        logger.info(f"Periodic sync completed: {synced_count} books")
                    
        except asyncio.CancelledError:
            logger.info("Background sync cancelled during shutdown")
            raise
        except Exception as e:
            logger.error(f"Background sync failed: {e}", exc_info=True)
    
    # Start background sync task and store reference
    import asyncio
    sync_task = asyncio.create_task(background_sync())
    
    # Print server information
    print("\n" + "="*60)
    print("CALIBRE OPENCLAW SERVER")
    print("="*60)
    print(f"Version: 1.0.0")
    print(f"Host: {settings.SERVER_HOST}")
    print(f"Port: {settings.SERVER_PORT}")
    print(f"\nServer URL: http://{settings.SERVER_HOST}:{settings.SERVER_PORT}")
    print(f"\nAPI Documentation:")
    print(f"  - Swagger UI: http://{settings.SERVER_HOST}:{settings.SERVER_PORT}/docs")
    print(f"  - ReDoc: http://{settings.SERVER_HOST}:{settings.SERVER_PORT}/redoc")
    print(f"  - OpenAPI JSON: http://{settings.SERVER_HOST}:{settings.SERVER_PORT}/openapi.json")
    print(f"\nSwarm Link (Windsurf):")
    print(f"  https://windsurf.ai/swarm?url=http://{settings.SERVER_HOST}:{settings.SERVER_PORT}/openapi.json")
    print(f"\nMain Endpoints:")
    print(f"  - GET  /api/books              - List all books")
    print(f"  - GET  /api/books/sync         - Sync books from Calibre")
    print(f"  - GET  /api/books/sync/status  - Check sync status")
    print(f"  - GET  /api/books/{{id}}         - Get book details")
    print(f"  - GET  /api/books/{{id}}/cover   - Get book cover (JPG)")
    print(f"  - GET  /api/books/{{id}}/pdf     - Get complete PDF")
    print(f"  - GET  /api/books/{{id}}/markdown - Get book as Markdown")
    print(f"  - GET  /api/search              - Search by metadata")
    print(f"  - POST /api/search/content      - Semantic content search")
    print(f"  - GET  /api/embeddings/status/{{id}} - Check embedding status")
    print(f"  - POST /api/embeddings/generate/{{id}} - Generate embeddings")
    print(f"  - GET  /api/embeddings/queue    - Get processing queue")
    print(f"  - GET  /api/stats/database      - Database statistics")
    print(f"  - GET  /api/stats/queries       - Query statistics")
    print(f"  - GET  /api/stats/overview     - Overview statistics")
    print(f"  - WS   /ws/stats                - Real-time statistics updates")
    print(f"  - GET  /dashboard               - Real-time dashboard UI")
    print(f"\nConfiguration:")
    print(f"  - Calibre DB: {settings.CALIBRE_DB_PATH}")
    print(f"  - Library Path: {settings.CALIBRE_LIBRARY_PATH}")
    print(f"  - Ollama: {settings.OLLAMA_HOST} ({settings.OLLAMA_MODEL})")
    print(f"  - PostgreSQL: {settings.POSTGRESQL_DB_HOST}:{settings.POSTGRESQL_DB_PORT}/{settings.POSTGRESQL_DB_DATABASE}")
    print(f"  - Log Dir: {settings.LOG_DIR}")
    print(f"  - Chunk Size: {settings.CHUNK_SIZE}, Overlap: {settings.CHUNK_OVERLAP}")
    print(f"  - Similarity Threshold: {settings.SIMILARITY_THRESHOLD}")
    print("="*60 + "\n")
    
    logger.info(f"Server starting on {settings.SERVER_HOST}:{settings.SERVER_PORT}")
    
    yield
    
    # Shutdown
    logger.info("Shutting down Calibre OpenClaw Server...")
    
    # Cancel background sync task if still running
    if sync_task and not sync_task.done():
        logger.info("Cancelling background sync task...")
        sync_task.cancel()
        try:
            await asyncio.wait_for(sync_task, timeout=5.0)
        except asyncio.CancelledError:
            logger.info("Background sync task cancelled")
        except asyncio.TimeoutError:
            logger.warning("Background sync task did not cancel in time")
        except Exception as e:
            logger.error(f"Error cancelling sync task: {e}")
    
    postgres_db.close_pool()
    logger.info("PostgreSQL connection pool closed")
    logger.info("Shutdown complete")


# Create FastAPI app
app = FastAPI(
    title="Calibre OpenClaw Server",
    description="REST API for managing Calibre library with semantic search capabilities",
    version="1.0.0",
    lifespan=lifespan
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Logging middleware
@app.middleware("http")
async def log_requests(request: Request, call_next):
    """Middleware to log all requests."""
    start_time = time.time()
    
    # Log request
    logger.info(
        f"Request: {request.method} {request.url.path}",
        extra={
            "method": request.method,
            "endpoint": str(request.url.path),
            "ip": request.client.host if request.client else None
        }
    )
    
    # Process request
    response = await call_next(request)
    
    # Calculate duration
    duration = time.time() - start_time
    
    # Log response
    logger.info(
        f"Response: {response.status_code}",
        extra={
            "status_code": response.status_code,
            "duration": duration
        }
    )
    
    return response


# Include routers
app.include_router(books.router)
app.include_router(search.router)
app.include_router(embeddings.router)
app.include_router(stats.router)
app.include_router(websocket.router)


# Root endpoint - Serve dashboard
@app.get("/", response_class=HTMLResponse)
async def root():
    """Root endpoint serves the dashboard."""
    from pathlib import Path
    dashboard_path = Path(__file__).parent / "dashboard.html"
    return FileResponse(dashboard_path)


# API info endpoint
@app.get("/api")
async def api_info():
    """API information endpoint."""
    return {
        "name": "Calibre OpenClaw Server",
        "version": "1.0.0",
        "description": "REST API for managing Calibre library with semantic search",
        "docs": "/docs",
        "openapi": "/openapi.json",
        "dashboard": "/"
    }


# Health check endpoint
@app.get("/health")
async def health_check():
    """Health check endpoint."""
    try:
        # Check database connection
        postgres_db.get_all_books(limit=1)
        return {"status": "healthy", "database": "connected"}
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "unhealthy", "database": "disconnected", "error": str(e)}
        )


# Global exception handler
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """Global exception handler."""
    logger.error(f"Unhandled exception: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"error": "Internal server error", "detail": str(exc)}
    )


if __name__ == "__main__":
    import uvicorn
    
    uvicorn.run(
        "app.main:app",
        host=settings.SERVER_HOST,
        port=settings.SERVER_PORT,
        reload=False,
        log_config=None  # Use our custom logger
    )
